services:
  # Flask Booking Services - Multiple Instances
  booking-service-1:
    build: ./booking-service
    container_name: booking-service-1
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - COCKROACHDB_HOST=${COCKROACHDB_HOST}
      - COCKROACHDB_PORT=${COCKROACHDB_PORT}
      - MONGODB_HOST=${MONGODB_HOST}
      - MONGODB_PORT=${MONGODB_PORT}
      - SERVICE_INSTANCE=1
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      cockroachdb:
        condition: service_healthy
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s

  booking-service-2:
    build: ./booking-service
    container_name: booking-service-2
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - COCKROACHDB_HOST=${COCKROACHDB_HOST}
      - COCKROACHDB_PORT=${COCKROACHDB_PORT}
      - MONGODB_HOST=${MONGODB_HOST}
      - MONGODB_PORT=${MONGODB_PORT}
      - SERVICE_INSTANCE=2
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      cockroachdb:
        condition: service_healthy
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s

  booking-service-3:
    build: ./booking-service
    container_name: booking-service-3
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - COCKROACHDB_HOST=${COCKROACHDB_HOST}
      - COCKROACHDB_PORT=${COCKROACHDB_PORT}
      - MONGODB_HOST=${MONGODB_HOST}
      - MONGODB_PORT=${MONGODB_PORT}
      - SERVICE_INSTANCE=3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      cockroachdb:
        condition: service_healthy
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s

  # redis container
  redis:
    image: redis:latest
    ports:
      - "${REDIS_PORT}:6379"  # Internal port is fixed to 6379
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 5
      start_period: 10s
      timeout: 3s
    restart: unless-stopped

  # cockroachdb container
  cockroachdb:
    image: cockroachdb/cockroach:latest
    ports:
      - "${COCKROACHDB_PORT}:26257"
      - "${COCKROACHDB_ADMIN_PORT}:8080"
    command: start-single-node --insecure
    volumes:
      - cockroachdb_data:/cockroach/cockroach-data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./backup:/cockroach/cockroach-data/extern/1/backup
      - ./init-cockroach.sh:/init-cockroach.sh
    entrypoint: ["/bin/sh", "/init-cockroach.sh"]
    healthcheck:
      test: ["CMD", "cockroach", "sql", "--insecure", "-e", "SELECT 1"]
      interval: 10s
      retries: 5
      start_period: 20s
    restart: unless-stopped

  # mongodb container
  mongodb:
    image: mongo:latest
    ports:
      - "${MONGODB_PORT}:27017"  # Internal port is fixed to 27017
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 10s
      retries: 5
      start_period: 15s
      timeout: 5s
    restart: unless-stopped

  # nginx container - Load Balancer
  nginx:
    image: nginx:latest
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - nginx_cache:/var/cache/nginx  # Mount cache directory
      - ./nginx/html:/usr/share/nginx/html  # Mount custom error pages
      - ./booking-service/app/static:/app/static
    environment:
      - BOOKING_SERVICE_HOST=${BOOKING_SERVICE_HOST}
      - BOOKING_SERVICE_PORT=${BOOKING_SERVICE_PORT}
      - NGINX_PORT=${NGINX_PORT}
    depends_on:
      - booking-service-1
      - booking-service-2
      - booking-service-3
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health", "||", "exit", "1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s
    restart: unless-stopped

# persistent storage for all containers
volumes:
  mongodb_data:
  cockroachdb_data:
  redis_data:
  nginx_cache: