version: '3.8'

services:
  booking-service:
    build: ./booking-service
    ports:
      - "5000:5000"
    depends_on:
      - kafka
      - redis
      - cockroachdb
      - mongodb

  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"

  redis:
    image: redis:latest
    ports:
      - "6380:6379"

  cockroachdb:
    image: cockroachdb/cockroach:latest
    ports:
      - "26257:26257"
      - "8080:8080"
    command: start-single-node --insecure

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/nginx/nginx.conf
    depends_on:
      - booking-service

volumes:
  mongodb_data: